import type { Metadata } from "next";
import { Providers } from './providers'

import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer/Footer";
import { NextUIProvider } from '@nextui-org/react';
import HomeNavbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hygraph",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <HomeNavbar/>
        </header>
        
        <Providers>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </Providers>

        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
